// Voxtral Transcribe — Copyright (c) 2026 Max Kloosterman
// Licensed under GPL-3.0 — see LICENSE for details
// https://github.com/maxonamission/voxtral-transcribe
import type { CustomCommand } from "../../shared/src/types";

/** Default built-in custom commands (table, callouts) */
export function getDefaultBuiltInCommands(): CustomCommand[] {
	return [
		{
			id: "builtin-table",
			builtIn: true,
			labels: {
				nl: "Tabel", en: "Table", fr: "Tableau", de: "Tabelle",
				es: "Tabla", pt: "Tabela", it: "Tabella", ru: "Таблица",
				zh: "表格", ja: "テーブル", ko: "테이블", hi: "टेबल", ar: "جدول",
			},
			type: "insert",
			insertText: "\n\n| Kolom 1 | Kolom 2 | Kolom 3 |\n| --- | --- | --- |\n| | | |\n",
			triggers: {
				nl: ["tabel", "nieuwe tabel"],
				en: ["table", "new table"],
				fr: ["tableau", "nouveau tableau"],
				de: ["tabelle", "neue tabelle"],
				es: ["tabla", "nueva tabla"],
				pt: ["tabela", "nova tabela"],
				it: ["tabella", "nuova tabella"],
				ru: ["таблица", "новая таблица"],
				zh: ["表格", "新表格"],
				ja: ["テーブル", "新しいテーブル"],
				ko: ["테이블", "새 테이블"],
				hi: ["टेबल", "नई टेबल"],
				ar: ["جدول", "جدول جديد"],
			},
		},
		{
			id: "builtin-callout",
			builtIn: true,
			labels: {
				nl: "Callout (opmerking)", en: "Callout (note)", fr: "Callout (note)",
				de: "Callout (Hinweis)", es: "Callout (nota)", pt: "Callout (nota)",
				it: "Callout (nota)", ru: "Заметка", zh: "标注（备注）",
				ja: "コールアウト（注釈）", ko: "콜아웃 (메모)", hi: "कॉलआउट (नोट)", ar: "تنبيه (ملاحظة)",
			},
			type: "insert",
			insertText: "\n\n> [!note]\n> ",
			triggers: {
				nl: ["callout", "opmerking", "notitie blok"],
				en: ["callout", "note block"],
				fr: ["callout", "bloc de note"],
				de: ["callout", "hinweisblock"],
				es: ["callout", "bloque de nota"],
				pt: ["callout", "bloco de nota"],
				it: ["callout", "blocco nota"],
				ru: ["заметка", "блок заметки"],
				zh: ["标注", "注释块"],
				ja: ["コールアウト", "注釈"],
				ko: ["콜아웃", "메모 블록"],
				hi: ["कॉलआउट", "नोट ब्लॉक"],
				ar: ["تنبيه", "كتلة ملاحظة"],
			},
		},
		{
			id: "builtin-warning",
			builtIn: true,
			labels: {
				nl: "Callout (waarschuwing)", en: "Callout (warning)", fr: "Callout (avertissement)",
				de: "Callout (Warnung)", es: "Callout (advertencia)", pt: "Callout (aviso)",
				it: "Callout (avviso)", ru: "Предупреждение", zh: "标注（警告）",
				ja: "コールアウト（警告）", ko: "콜아웃 (경고)", hi: "कॉलआउट (चेतावनी)", ar: "تنبيه (تحذير)",
			},
			type: "insert",
			insertText: "\n\n> [!warning]\n> ",
			triggers: {
				nl: ["waarschuwing", "waarschuwing blok"],
				en: ["warning", "warning block"],
				fr: ["avertissement"],
				de: ["warnung"],
				es: ["advertencia"],
				pt: ["aviso"],
				it: ["avviso"],
				ru: ["предупреждение"],
				zh: ["警告"],
				ja: ["警告"],
				ko: ["경고"],
				hi: ["चेतावनी"],
				ar: ["تحذير"],
			},
		},
		{
			id: "builtin-tip",
			builtIn: true,
			labels: {
				nl: "Callout (tip)", en: "Callout (tip)", fr: "Callout (astuce)",
				de: "Callout (Tipp)", es: "Callout (consejo)", pt: "Callout (dica)",
				it: "Callout (suggerimento)", ru: "Совет", zh: "标注（提示）",
				ja: "コールアウト（ヒント）", ko: "콜아웃 (팁)", hi: "कॉलआउट (सुझाव)", ar: "تنبيه (نصيحة)",
			},
			type: "insert",
			insertText: "\n\n> [!tip]\n> ",
			triggers: {
				nl: ["tip", "tip blok"],
				en: ["tip", "tip block"],
				fr: ["astuce"],
				de: ["tipp"],
				es: ["consejo"],
				pt: ["dica"],
				it: ["suggerimento"],
				ru: ["совет"],
				zh: ["提示"],
				ja: ["ヒント"],
				ko: ["팁"],
				hi: ["सुझाव"],
				ar: ["نصيحة"],
			},
		},
	];
}
